#PBS -l nodes=1:ppn=1
#PBS -j oe
#PBS -o ${out}.results.txt
#PBS -V 
#PBS -l mem=16g
cd ${cwd}

echo ${cwd}
for bam in $out/*._1.bam
do
    p1=`basename $bam`
    p2=`echo $p1 | sed 's#._1.bam#._2.bam#g'` # Thanks to name mangling, garunteed to be ._1 and ._2
    bedpeout=`echo $p1 | sed 's#._1.bam##g'`

    echo collect_valid_pairs.py $out/$p1 $out/$p2 $bedpeout.bedpe $bedpeout.out
done

echo cat $out/*.bedpe > $out/../$sam_name.bedpe
echo tail -n +1 $out/*.out >$out/../$sam_name.summary.out
