#PBS -l nodes=1:ppn=2
#PBS -j oe
#PBS -o ${out}.step2.results.txt
#PBS -V 
#PBS -l mem=32g
cd ${cwd}

for bam in $out/*_1.bam
do
    p1=`basename $bam`
    p2=`echo $p1 | sed 's#_1.bam#_2.bam#g'` # Thanks to name mangling, garunteed to be _1 and _2
    bedpeout=`echo $p1 | sed 's#_1.bam##g'`

    collect_valid_pairs.py $out/$p1 $out/$p2 $out/$bedpeout.bedpe.gz >$out/$bedpeout.out
done

# Slower, but more portable.
gunzip -c $out/*.bedpe.gz | sort -T . | uniq | gzip > $out/../$sam_name.bedpe.gz
tail -n +1 $out/*.out >$out/../$sam_name.summary.out


